# Dataset config
dataset:
  name: animals
  batch_size: 32
  num_workers: 4
  config:
    data_root: /data/kaggle/flowers17
    split_ratios:
      train: 0.75
      val: 0.0
      test: 0.25
    random_state: 42
  transforms:
    resize: 256
    crop: 224
    random_resized_crop:
      size: 224
      scale: [0.7, 1.0]  # Less aggressive crop (70-100% of original)
      # ratio: [0.75, 1.33]  # Optional: aspect ratio range (default: [3/4, 4/3])
    # Commented out to use default normalization values for the pretrained model
    # If you traing the model from scratch, consider uncommenting and adjusting these values
    # normalize:
    #   mean: [0.461, 0.437, 0.392]
    #   std: [0.272, 0.263, 0.263]
    random_horizontal_flip: true
    color_jitter:  # NEW: Add color augmentation
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    random_affine:
      degrees: 15
      translate: [0.1, 0.1]
      # shear: 0.2
      # scale: [0.8, 1.0]

# Model config
model:
  backbone: vgg16_logistic
  num_classes: 17

# Loss config
loss:
  type: cross_entropy

# Optimizer config
optimizer:
  type: SGD
  lr: 0.01
  weight_decay: 0.01 # 0.01 worked best in experiments
  momentum: 0.0
  # Cross-validation is only used in optimize_hyperparameters.py
  # main.py ignores this section
  cross_validation:
    weight_decay: [10.0, 1.0, 0.1, 0.01, 0.001, 0.0001]
    folds: 5

# Scheduler config
scheduler:
  type: none

# Training config
training:
  epochs: 50
  device: auto
  checkpoint_path: flower17_vgg16_logistic.pth
